In [1]:
!pip install pandas pyreadstat

Requirement already satisfied: pandas in c:\users\user\anaconda3\lib\site-packages (2.3.3)
Collecting pyreadstat
  Downloading pyreadstat-1.3.5-cp313-cp313-win_amd64.whl.metadata (1.3 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2025.2)
Collecting narwhals>=2.10.1 (from pyreadstat)
  Downloading narwhals-2.24.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pyreadstat-1.3.5-cp313-cp313-win_amd64.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------- ----------------------------- 0.5/2.0 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------- 2.0/2.0 MB 6.4 MB/s  0:00:00
Downloading narwhals-2.24.0-py3-none-any.whl (461 kB)
Installing collected packages: narwhals, pyreadstat

  Attempting uninstall: narwhals

    Found existing installation: narwhals 2.7.0

    Uninstalling narwhals-2.7.0:

      Successfully uninstalled narwhals-2.7.0

   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   -------------------- ------------------- 1/2 [pyreadstat]
   ---------------------------------------- 2/2 [pyreadstat]

Successfully installed narwhals-2.24.0 pyreadstat-1.3.5

In [11]:
!pip install pandas pyreadstat

Requirement already satisfied: pandas in c:\users\user\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: pyreadstat in c:\users\user\anaconda3\lib\site-packages (1.3.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: narwhals>=2.10.1 in c:\users\user\anaconda3\lib\site-packages (from pyreadstat) (2.24.0)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [39]:
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [126]:
# Educación (Módulo 03)
df3 = pd.read_stata('enaho01a_2020_300.dta')
df3.head()

,aÑo,mes,conglome,vivienda,hogar,codperso,ubigeo,dominio,estrato,codinfor,...,i311d_2,i311d_3,i311d_4,i311d_5,i311d_6,i311d_7,i3121c,i3122c,i315b,factor
0,2020,07,005052,003,11,01,010702,selva,"de 2,000 a 19,999 habitantes",01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,895.776489
1,2020,07,005052,003,11,02,010702,selva,"de 2,000 a 19,999 habitantes",02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,825.084900
2,2020,07,005052,003,11,03,010702,selva,"de 2,000 a 19,999 habitantes",02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1069.304199
3,2020,07,005052,003,11,04,010702,selva,"de 2,000 a 19,999 habitantes",04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1029.342407
4,2020,07,005052,005,11,01,010702,selva,"de 2,000 a 19,999 habitantes",01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,895.776489

In [138]:
# Samaria (Módulo 34) - Pobreza Monetaria (Enfoque de Ingresos y Gastos)
df34 = pd.read_spss('Sumaria-2020.sav')
df34.head()

,AÑO,MES,CONGLOME,VIVIENDA,HOGAR,UBIGEO,DOMINIO,ESTRATO,MIEPERHO,TOTMIEHO,...,LINEA,POBREZA,TIPOCUESTIONARIO,TIPOENTREVISTA,FACTOR07,NCONGLOME,SUB_CONGLOME,LINEAV_RPL,LINEAV,POBREZAV
0,2020,01,005009,012,11,010101,sierra norte,"de 20,000 a 49,999 habitantes",2.0,2.0,...,303.520996,No Pobre,Cuestionario completo - Antes de la emergencia...,presencial,149.202744,007076,00,657.0,560.468506,No Vulnerable
1,2020,01,005009,041,11,010101,sierra norte,"de 20,000 a 49,999 habitantes",2.0,2.0,...,303.520996,No Pobre,Cuestionario completo - Antes de la emergencia...,presencial,149.202744,007076,00,657.0,553.731506,No Vulnerable
2,2020,01,005009,098,11,010101,sierra norte,"de 20,000 a 49,999 habitantes",6.0,6.0,...,303.520996,No Pobre,Cuestionario completo - Antes de la emergencia...,presencial,149.202744,007076,00,657.0,547.194031,Vulnerable No pobre
3,2020,01,005015,007,11,010101,sierra norte,"de 20,000 a 49,999 habitantes",4.0,4.0,...,303.520996,No Pobre,Cuestionario completo - Antes de la emergencia...,presencial,70.492592,007089,00,657.0,556.025330,No Vulnerable
4,2020,01,005015,019,11,010101,sierra norte,"de 20,000 a 49,999 habitantes",4.0,4.0,...,303.520996,No Pobre,Cuestionario completo - Antes de la emergencia...,presencial,70.492592,007089,00,657.0,548.526917,No Vulnerable

In [139]:
# Sustraccion de columnas de interes
educacion = df3[['mes','conglome', 'vivienda', 'hogar', 'p203', 'p301a', 'p208a', 'p207']]
monetario = df34[['MES','CONGLOME', 'VIVIENDA', 'HOGAR', 'POBREZA', 'MIEPERHO', 'DOMINIO', 'ESTRATO', 'FACTOR07']]

# convertimos a minuscula los titulos de la tabla monetario
monetario.columns = monetario.columns.str.lower()

# convierto a csv para trabajar en power bi
educacion.to_csv('educacion.csv',index=False, encoding='utf-8-sig')
monetario.to_csv('monetario.csv',index=False, encoding='utf-8-sig')

In [140]:
print(educacion.columns)
print(monetario.columns)

Index(['mes', 'conglome', 'vivienda', 'hogar', 'p203', 'p301a', 'p208a',
       'p207'],
      dtype='object')
Index(['mes', 'conglome', 'vivienda', 'hogar', 'pobreza', 'mieperho',
       'dominio', 'estrato', 'factor07'],
      dtype='object')

In [141]:
# renombro las columnas
educacion.rename(columns={'p203':'parentesco','p301a':'nivel_educativo','p208a':'edad_jefe','p207':'sexo_jefe'}, inplace=True)
monetario.rename(columns={ 'mieperho':'tamano_hogar'}, inplace=True)

educacion.columns,monetario.columns

C:\Users\User\AppData\Local\Temp\ipykernel_31604\3666796220.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  educacion.rename(columns={'p203':'parentesco','p301a':'nivel_educativo','p208a':'edad_jefe','p207':'sexo_jefe'}, inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_31604\3666796220.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  monetario.rename(columns={ 'mieperho':'tamano_hogar'}, inplace=True)

(Index(['mes', 'conglome', 'vivienda', 'hogar', 'parentesco', 'nivel_educativo',
        'edad_jefe', 'sexo_jefe'],
       dtype='object'),
 Index(['mes', 'conglome', 'vivienda', 'hogar', 'pobreza', 'tamano_hogar',
        'dominio', 'estrato', 'factor07'],
       dtype='object'))

In [142]:
# discretizo sexo del jefe del hogar
educacion['sexo_jefe'] = educacion['sexo_jefe'].apply(lambda x: 'Hombre' if x==1 else 'Mujer')
educacion['sexo_jefe']

C:\Users\User\AppData\Local\Temp\ipykernel_31604\610970052.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  educacion['sexo_jefe'] = educacion['sexo_jefe'].apply(lambda x: 'Hombre' if x==1 else 'Mujer')

0        Hombre
1         Mujer
2         Mujer
3        Hombre
4        Hombre
          ...
27396     Mujer
27397    Hombre
27398     Mujer
27399     Mujer
27400    Hombre
Name: sexo_jefe, Length: 27401, dtype: object

In [143]:
# filtrar solo los jefes de Hogar
jefes = educacion[educacion['parentesco'] == 1].copy()
jefes.head()

,mes,conglome,vivienda,hogar,parentesco,nivel_educativo,edad_jefe,sexo_jefe
0,07,005052,003,11,1,sup. univ. completa,57,Hombre
4,07,005052,005,11,1,primaria completa,64,Hombre
7,07,005052,010,11,1,primaria incompleta,68,Hombre
9,07,005052,013,11,1,primaria completa,59,Hombre
14,07,005052,016,11,1,sup. no univ. incompleta,32,Hombre

In [144]:
# Verifico categoria de pobreza en la tabla monetario
monetario['pobreza'].value_counts()

pobreza
No Pobre            26766
Pobre No Extremo     6272
Pobre Extremo        1452
Name: count, dtype: int64

In [145]:
# Crear variable binaria de pobreza
monetario['pobre_binario'] = monetario['pobreza'].apply(lambda x: 1 if x=='Pobre No Extremo' or x=='Pobre Extremo' else 0)
monetario.head()
monetario['pobre_binario'].value_counts()

C:\Users\User\AppData\Local\Temp\ipykernel_31604\1852327445.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  monetario['pobre_binario'] = monetario['pobreza'].apply(lambda x: 1 if x=='Pobre No Extremo' or x=='Pobre Extremo' else 0)

pobre_binario
0    26766
1     7724
Name: count, dtype: int64

In [146]:
# Hacemos un modelo Probit/Logit
"""
nivel educativo del jefe de hogar y la pobreza monetaria antes y después 
de tu modelo Probit/Logit.

Análisis Exploratorio (Descriptivo) y Resultados Econométricos.
"""

'\nnivel educativo del jefe de hogar y la pobreza monetaria antes y después \nde tu modelo Probit/Logit.\n\nAnálisis Exploratorio (Descriptivo) y Resultados Econométricos.\n'

In [147]:
# juntamos ambas tablas por 'conglome', 'vivienda', 'hogar'
ENAHO = pd.merge(
    educacion, monetario,
    on = ['mes','conglome', 'vivienda', 'hogar'],
    how = 'inner'
)

In [148]:
# convierto a csv para trabajar en power bi
educacion.to_csv('educacion.csv',index=False, encoding='utf-8-sig')
monetario.to_csv('monetario.csv',index=False, encoding='utf-8-sig')
ENAHO.to_csv('ENAHO.csv',index=False, encoding='utf-8-sig')

In [150]:
ENAHO.columns

Index(['mes', 'conglome', 'vivienda', 'hogar', 'parentesco', 'nivel_educativo',
       'edad_jefe', 'sexo_jefe', 'pobreza', 'tamano_hogar', 'dominio',
       'estrato', 'factor07', 'pobre_binario'],
      dtype='object')

In [155]:
ENAHO['nivel_educativo'].value_counts()

nivel_educativo
primaria incompleta         5574
secundaria completa         5442
secundaria incompleta       4244
primaria completa           2912
sup. no univ. completa      1701
sup. univ. completa         1628
sin nivel                   1523
educación inicial           1372
sup. univ. incompleta       1273
sup. no univ. incompleta     942
maestría / doctorado         247
básica especial               17
Name: count, dtype: int64

TypeError: Model.from_formula() missing 1 required positional argument: 'formula'